[package]
name = "load_balancer"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "load_balancer"
path = "src/main.rs"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
